export { default as api, tenantPath } from "./api";
export * from "./authService";
export * from "./userService";
export * from "./studentService";
export * from "./collegeService";
export * from "./courseService";
export * from "./feeService";
export * from "./followupService";
export * from "./dashboardService";
export * from "./settingsService";
