/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollegesRouteImport } from './routes/colleges'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as CollegesIdRouteImport } from './routes/colleges_.$id'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminFollowupsRouteImport } from './routes/admin.followups'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminCollegesRouteImport } from './routes/admin.colleges'
import { Route as AdminStudentsNewRouteImport } from './routes/admin.students_.new'
import { Route as AdminStudentsIdRouteImport } from './routes/admin.students_.$id'
import { Route as AdminCollegesNewRouteImport } from './routes/admin.colleges_.new'
import { Route as AdminCollegesIdRouteImport } from './routes/admin.colleges_.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesRoute = CollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const CollegesIdRoute = CollegesIdRouteImport.update({
  id: '/colleges_/$id',
  path: '/colleges/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFollowupsRoute = AdminFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollegesRoute = AdminCollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsNewRoute = AdminStudentsNewRouteImport.update({
  id: '/students_/new',
  path: '/students/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsIdRoute = AdminStudentsIdRouteImport.update({
  id: '/students_/$id',
  path: '/students/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollegesNewRoute = AdminCollegesNewRouteImport.update({
  id: '/colleges_/new',
  path: '/colleges/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollegesIdRoute = AdminCollegesIdRouteImport.update({
  id: '/colleges_/$id',
  path: '/colleges/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/colleges': typeof CollegesRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/followups': typeof AdminFollowupsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/colleges/$id': typeof AdminCollegesIdRoute
  '/admin/colleges/new': typeof AdminCollegesNewRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/admin/students/new': typeof AdminStudentsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/colleges': typeof CollegesRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/followups': typeof AdminFollowupsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/colleges/$id': typeof AdminCollegesIdRoute
  '/admin/colleges/new': typeof AdminCollegesNewRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/admin/students/new': typeof AdminStudentsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/colleges': typeof CollegesRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/followups': typeof AdminFollowupsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/colleges_/$id': typeof CollegesIdRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/admin/colleges_/$id': typeof AdminCollegesIdRoute
  '/admin/colleges_/new': typeof AdminCollegesNewRoute
  '/admin/students_/$id': typeof AdminStudentsIdRoute
  '/admin/students_/new': typeof AdminStudentsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/colleges'
    | '/contact'
    | '/courses'
    | '/login'
    | '/admin/colleges'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/fees'
    | '/admin/followups'
    | '/admin/settings'
    | '/admin/students'
    | '/colleges/$id'
    | '/courses/$slug'
    | '/admin/colleges/$id'
    | '/admin/colleges/new'
    | '/admin/students/$id'
    | '/admin/students/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/colleges'
    | '/contact'
    | '/courses'
    | '/login'
    | '/admin/colleges'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/fees'
    | '/admin/followups'
    | '/admin/settings'
    | '/admin/students'
    | '/colleges/$id'
    | '/courses/$slug'
    | '/admin/colleges/$id'
    | '/admin/colleges/new'
    | '/admin/students/$id'
    | '/admin/students/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/colleges'
    | '/contact'
    | '/courses'
    | '/login'
    | '/admin/colleges'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/fees'
    | '/admin/followups'
    | '/admin/settings'
    | '/admin/students'
    | '/colleges_/$id'
    | '/courses/$slug'
    | '/admin/colleges_/$id'
    | '/admin/colleges_/new'
    | '/admin/students_/$id'
    | '/admin/students_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CollegesRoute: typeof CollegesRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  LoginRoute: typeof LoginRoute
  CollegesIdRoute: typeof CollegesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges': {
      id: '/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof CollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/colleges_/$id': {
      id: '/colleges_/$id'
      path: '/colleges/$id'
      fullPath: '/colleges/$id'
      preLoaderRoute: typeof CollegesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/followups': {
      id: '/admin/followups'
      path: '/followups'
      fullPath: '/admin/followups'
      preLoaderRoute: typeof AdminFollowupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colleges': {
      id: '/admin/colleges'
      path: '/colleges'
      fullPath: '/admin/colleges'
      preLoaderRoute: typeof AdminCollegesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students_/new': {
      id: '/admin/students_/new'
      path: '/students/new'
      fullPath: '/admin/students/new'
      preLoaderRoute: typeof AdminStudentsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students_/$id': {
      id: '/admin/students_/$id'
      path: '/students/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AdminStudentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colleges_/new': {
      id: '/admin/colleges_/new'
      path: '/colleges/new'
      fullPath: '/admin/colleges/new'
      preLoaderRoute: typeof AdminCollegesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colleges_/$id': {
      id: '/admin/colleges_/$id'
      path: '/colleges/$id'
      fullPath: '/admin/colleges/$id'
      preLoaderRoute: typeof AdminCollegesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCollegesRoute: typeof AdminCollegesRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminFollowupsRoute: typeof AdminFollowupsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminCollegesIdRoute: typeof AdminCollegesIdRoute
  AdminCollegesNewRoute: typeof AdminCollegesNewRoute
  AdminStudentsIdRoute: typeof AdminStudentsIdRoute
  AdminStudentsNewRoute: typeof AdminStudentsNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCollegesRoute: AdminCollegesRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminFollowupsRoute: AdminFollowupsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminCollegesIdRoute: AdminCollegesIdRoute,
  AdminCollegesNewRoute: AdminCollegesNewRoute,
  AdminStudentsIdRoute: AdminStudentsIdRoute,
  AdminStudentsNewRoute: AdminStudentsNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CollegesRoute: CollegesRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  LoginRoute: LoginRoute,
  CollegesIdRoute: CollegesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
